#Telecom X – Parte 2: Predicción de Cancelación (Churn)

##Objetivos del Desafío

Preparar los datos para el modelado (tratamiento, codificación, normalización).

Realizar análisis de correlación y selección de variables.

Entrenar dos o más modelos de clasificación.

Evaluar el rendimiento de los modelos con métricas.

Interpretar los resultados, incluyendo la importancia de las variables.

Crear una conclusión estratégica señalando los principales factores que influyen en la cancelación.

🎯 Misión

Tu nueva misión es desarrollar modelos predictivos capaces de prever qué clientes tienen mayor probabilidad de cancelar sus servicios.

La empresa quiere anticiparse al problema de la cancelación, y te corresponde a ti construir un pipeline robusto para esta etapa inicial de modelado.

##Preparación de los Datos

###Extracción del Archivo Tratado
Extracción del Archivo Tratado Carga el archivo CSV que contiene los datos tratados anteriormente.

In [ ]:
import pandas as pd
datos = pd.read_csv('https://raw.githubusercontent.com/fasalgad/TelecomX_LATAM-parte-2/refs/heads/main/datos_tratados.csv')
datos.head()

,customerid,churn,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,charges_monthly,charges_total,cuentas_diarias
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,No,Yes,Yes,No,One year,Yes,Mailed check,65.6,593.3,2.186667
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,Yes,Month-to-month,No,Mailed check,59.9,542.4,1.996667
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.9,280.85,2.463333
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.0,1237.85,3.266667
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.9,267.4,2.796667

###Eliminación de Columnas Irrelevantes
Elimina columnas que no aportan valor al análisis o a los modelos predictivos, como identificadores únicos (por ejemplo, el ID del cliente). Estas columnas no ayudan en la predicción de la cancelación y pueden incluso perjudicar el desempeño de los modelos.

In [ ]:
datos.columns

Index(['customerid', 'churn', 'gender', 'seniorcitizen', 'partner',
       'dependents', 'tenure', 'phoneservice', 'multiplelines',
       'internetservice', 'onlinesecurity', 'onlinebackup', 'deviceprotection',
       'techsupport', 'streamingtv', 'streamingmovies', 'contract',
       'paperlessbilling', 'paymentmethod', 'charges_monthly', 'charges_total',
       'cuentas_diarias'],
      dtype='object')

In [ ]:
datos.index

RangeIndex(start=0, stop=7267, step=1)

In [ ]:
if 'customerid' in datos.columns:
    datos = datos.drop(columns=['customerid'])
    print("Columna 'customerid' removida con éxito.")
print(datos.head())

Columna 'customerid' removida con éxito.
  churn  gender  seniorcitizen partner dependents  tenure phoneservice  \
0    No  Female              0     Yes        Yes       9          Yes
1    No    Male              0      No         No       9          Yes
2   Yes    Male              0      No         No       4          Yes
3   Yes    Male              1     Yes         No      13          Yes
4   Yes  Female              1     Yes         No       3          Yes

  multiplelines internetservice onlinesecurity  ... deviceprotection  \
0            No             DSL             No  ...               No
1           Yes             DSL             No  ...               No
2            No     Fiber optic             No  ...              Yes
3            No     Fiber optic             No  ...              Yes
4            No     Fiber optic             No  ...               No

  techsupport streamingtv streamingmovies        contract paperlessbilling  \
0         Yes         Yes              No        One year              Yes
1          No          No             Yes  Month-to-month               No
2          No          No              No  Month-to-month              Yes
3          No         Yes             Yes  Month-to-month              Yes
4         Yes         Yes              No  Month-to-month              Yes

      paymentmethod charges_monthly  charges_total cuentas_diarias
0      Mailed check            65.6          593.3        2.186667
1      Mailed check            59.9          542.4        1.996667
2  Electronic check            73.9         280.85        2.463333
3  Electronic check            98.0        1237.85        3.266667
4      Mailed check            83.9          267.4        2.796667

[5 rows x 21 columns]

In [ ]:
datos.head()

,churn,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,charges_monthly,charges_total,cuentas_diarias
0,No,Female,0,Yes,Yes,9,Yes,No,DSL,No,...,No,Yes,Yes,No,One year,Yes,Mailed check,65.6,593.3,2.186667
1,No,Male,0,No,No,9,Yes,Yes,DSL,No,...,No,No,No,Yes,Month-to-month,No,Mailed check,59.9,542.4,1.996667
2,Yes,Male,0,No,No,4,Yes,No,Fiber optic,No,...,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.9,280.85,2.463333
3,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.0,1237.85,3.266667
4,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,No,...,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.9,267.4,2.796667

###Encoding

Transforma las variables categóricas a formato numérico para hacerlas compatibles con los algoritmos de machine learning. Utiliza un método de codificación adecuado, como one-hot encoding.

In [ ]:
datos.sample(2)

,churn,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,charges_monthly,charges_total,cuentas_diarias
7215,No,Male,0,No,No,72,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Electronic check,118.20,8547.15,3.940000
7176,No,Female,0,Yes,Yes,17,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,No,Mailed check,20.75,418.25,0.691667

In [ ]:
datos.columns

Index(['churn', 'gender', 'seniorcitizen', 'partner', 'dependents', 'tenure',
       'phoneservice', 'multiplelines', 'internetservice', 'onlinesecurity',
       'onlinebackup', 'deviceprotection', 'techsupport', 'streamingtv',
       'streamingmovies', 'contract', 'paperlessbilling', 'paymentmethod',
       'charges_monthly', 'charges_total', 'cuentas_diarias'],
      dtype='object')

In [ ]:
datos.index

RangeIndex(start=0, stop=7267, step=1)

In [ ]:
datos["churn"] = datos["churn"].map(lambda x: {"Yes":1,"No":0}.get(x, x))

In [ ]:
datos.sample(1)

,churn,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,charges_monthly,charges_total,cuentas_diarias
1542,No,Male,0,Yes,Yes,52,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,24.55,1331.05,0.818333

In [ ]:
print(datos.info())
print(datos.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   churn             7267 non-null   object
 1   gender            7267 non-null   object
 2   seniorcitizen     7267 non-null   int64
 3   partner           7267 non-null   object
 4   dependents        7267 non-null   object
 5   tenure            7267 non-null   int64
 6   phoneservice      7267 non-null   object
 7   multiplelines     7267 non-null   object
 8   internetservice   7267 non-null   object
 9   onlinesecurity    7267 non-null   object
 10  onlinebackup      7267 non-null   object
 11  deviceprotection  7267 non-null   object
 12  techsupport       7267 non-null   object
 13  streamingtv       7267 non-null   object
 14  streamingmovies   7267 non-null   object
 15  contract          7267 non-null   object
 16  paperlessbilling  7267 non-null   object
 17  paymentmethod     7267 non-null   object
 18  charges_monthly   7267 non-null   float64
 19  charges_total     7267 non-null   object
 20  cuentas_diarias   7267 non-null   float64
dtypes: float64(2), int64(2), object(17)
memory usage: 1.2+ MB
None
       seniorcitizen       tenure  charges_monthly  cuentas_diarias
count    7267.000000  7267.000000      7267.000000      7267.000000
mean        0.162653    32.346498        64.720098         2.157337
std         0.369074    24.571773        30.129572         1.004319
min         0.000000     0.000000        18.250000         0.608333
25%         0.000000     9.000000        35.425000         1.180833
50%         0.000000    29.000000        70.300000         2.343333
75%         0.000000    55.000000        89.875000         2.995833
max         1.000000    72.000000       118.750000         3.958333

In [ ]:
binary_cols = [
    "partner",
    "dependents",
    "phoneservice",
    "paperlessbilling",
    "churn"
]

for col in binary_cols:
    datos[col] = datos[col].map(lambda x: {"Yes":1,"No":0}.get(x, x))

datos.head()

,churn,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,charges_monthly,charges_total,cuentas_diarias
0,0,Female,0,1,1,9,1,No,DSL,No,...,No,Yes,Yes,No,One year,1,Mailed check,65.6,593.3,2.186667
1,0,Male,0,0,0,9,1,Yes,DSL,No,...,No,No,No,Yes,Month-to-month,0,Mailed check,59.9,542.4,1.996667
2,1,Male,0,0,0,4,1,No,Fiber optic,No,...,Yes,No,No,No,Month-to-month,1,Electronic check,73.9,280.85,2.463333
3,1,Male,1,1,0,13,1,No,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,1,Electronic check,98.0,1237.85,3.266667
4,1,Female,1,1,0,3,1,No,Fiber optic,No,...,No,Yes,Yes,No,Month-to-month,1,Mailed check,83.9,267.4,2.796667

In [ ]:
from sklearn.preprocessing import OneHotEncoder

categorical_cols = [
    "gender",
    "multiplelines",
    "internetservice",
    "onlinesecurity",
    "onlinebackup",
    "deviceprotection",
    "techsupport",
    "streamingtv",
    "streamingmovies",
    "contract",
    "paymentmethod"
]

encoder = OneHotEncoder(handle_unknown="ignore", sparse_output=False)

encoded = encoder.fit_transform(datos[categorical_cols])

encoded_df = pd.DataFrame(
    encoded,
    columns=encoder.get_feature_names_out(categorical_cols),
    index=datos.index
)

datos = pd.concat([datos.drop(columns=categorical_cols), encoded_df], axis=1)

In [ ]:
datos.sample(20)

,churn,seniorcitizen,partner,dependents,tenure,phoneservice,paperlessbilling,charges_monthly,charges_total,cuentas_diarias,...,streamingmovies_No,streamingmovies_No internet service,streamingmovies_Yes,contract_Month-to-month,contract_One year,contract_Two year,paymentmethod_Bank transfer (automatic),paymentmethod_Credit card (automatic),paymentmethod_Electronic check,paymentmethod_Mailed check
5101,0,0,0,0,6,1,0,20.00,109.2,0.666667,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
804,0,0,1,1,50,1,1,84.15,4164.4,2.805000,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
2226,0,0,1,1,4,1,1,19.95,82.9,0.665000,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
6517,0,0,1,0,56,1,0,24.30,1261.7,0.810000,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1891,0,1,1,0,31,1,0,89.45,2807.65,2.981667,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
455,1,1,1,0,47,1,0,80.35,3825.85,2.678333,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
6274,0,0,1,0,51,1,1,75.20,3901.25,2.506667,...,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
7092,0,0,0,0,38,1,1,69.50,2625.25,2.316667,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
618,1,0,0,0,54,1,1,103.95,5639.05,3.465000,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
683,0,0,1,1,37,1,0,19.80,677.05,0.660000,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
4541,0,0,0,0,1,0,1,35.45,35.45,1.181667,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1908,0,0,1,1,55,1,0,100.90,5448.6,3.363333,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
5823,0,0,0,0,3,1,0,74.40,215.8,2.480000,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
6847,0,0,1,1,27,1,1,85.20,2151.6,2.840000,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
5587,0,0,0,1,8,0,1,38.50,330.8,1.283333,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
3812,0,1,1,0,31,1,1,84.85,2633.4,2.828333,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
4780,0,0,0,0,13,0,1,30.85,394.1,1.028333,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
294,0,1,0,0,9,1,0,49.20,447.9,1.640000,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
4981,0,0,1,0,56,1,1,107.25,6033.3,3.575000,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
6102,0,0,1,1,72,1,1,66.50,4811.6,2.216667,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0

In [ ]:
datos = datos.drop(columns=[
    "gender_Female",
    "multiplelines_No",
    "internetservice_No",
    "onlinesecurity_No"
])

print(datos.columns)
datos.info()

Index(['churn', 'seniorcitizen', 'partner', 'dependents', 'tenure',
       'phoneservice', 'paperlessbilling', 'charges_monthly', 'charges_total',
       'cuentas_diarias', 'gender_Male', 'multiplelines_No phone service',
       'multiplelines_Yes', 'internetservice_DSL',
       'internetservice_Fiber optic', 'onlinesecurity_No internet service',
       'onlinesecurity_Yes', 'onlinebackup_No',
       'onlinebackup_No internet service', 'onlinebackup_Yes',
       'deviceprotection_No', 'deviceprotection_No internet service',
       'deviceprotection_Yes', 'techsupport_No',
       'techsupport_No internet service', 'techsupport_Yes', 'streamingtv_No',
       'streamingtv_No internet service', 'streamingtv_Yes',
       'streamingmovies_No', 'streamingmovies_No internet service',
       'streamingmovies_Yes', 'contract_Month-to-month', 'contract_One year',
       'contract_Two year', 'paymentmethod_Bank transfer (automatic)',
       'paymentmethod_Credit card (automatic)',
       'paymentmethod_Electronic check', 'paymentmethod_Mailed check'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 39 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   churn                                    7267 non-null   int64
 1   seniorcitizen                            7267 non-null   int64
 2   partner                                  7267 non-null   int64
 3   dependents                               7267 non-null   int64
 4   tenure                                   7267 non-null   int64
 5   phoneservice                             7267 non-null   int64
 6   paperlessbilling                         7267 non-null   int64
 7   charges_monthly                          7267 non-null   float64
 8   charges_total                            7267 non-null   object
 9   cuentas_diarias                          7267 non-null   float64
 10  gender_Male                              7267 non-null   float64
 11  multiplelines_No phone service           7267 non-null   float64
 12  multiplelines_Yes                        7267 non-null   float64
 13  internetservice_DSL                      7267 non-null   float64
 14  internetservice_Fiber optic              7267 non-null   float64
 15  onlinesecurity_No internet service       7267 non-null   float64
 16  onlinesecurity_Yes                       7267 non-null   float64
 17  onlinebackup_No                          7267 non-null   float64
 18  onlinebackup_No internet service         7267 non-null   float64
 19  onlinebackup_Yes                         7267 non-null   float64
 20  deviceprotection_No                      7267 non-null   float64
 21  deviceprotection_No internet service     7267 non-null   float64
 22  deviceprotection_Yes                     7267 non-null   float64
 23  techsupport_No                           7267 non-null   float64
 24  techsupport_No internet service          7267 non-null   float64
 25  techsupport_Yes                          7267 non-null   float64
 26  streamingtv_No                           7267 non-null   float64
 27  streamingtv_No internet service          7267 non-null   float64
 28  streamingtv_Yes                          7267 non-null   float64
 29  streamingmovies_No                       7267 non-null   float64
 30  streamingmovies_No internet service      7267 non-null   float64
 31  streamingmovies_Yes                      7267 non-null   float64
 32  contract_Month-to-month                  7267 non-null   float64
 33  contract_One year                        7267 non-null   float64
 34  contract_Two year                        7267 non-null   float64
 35  paymentmethod_Bank transfer (automatic)  7267 non-null   float64
 36  paymentmethod_Credit card (automatic)    7267 non-null   float64
 37  paymentmethod_Electronic check           7267 non-null   float64
 38  paymentmethod_Mailed check               7267 non-null   float64
dtypes: float64(31), int64(7), object(1)
memory usage: 2.2+ MB

In [ ]:
datos["charges_total"] = pd.to_numeric(datos["charges_total"], errors="coerce")
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 39 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   churn                                    7267 non-null   int64
 1   seniorcitizen                            7267 non-null   int64
 2   partner                                  7267 non-null   int64
 3   dependents                               7267 non-null   int64
 4   tenure                                   7267 non-null   int64
 5   phoneservice                             7267 non-null   int64
 6   paperlessbilling                         7267 non-null   int64
 7   charges_monthly                          7267 non-null   float64
 8   charges_total                            7256 non-null   float64
 9   cuentas_diarias                          7267 non-null   float64
 10  gender_Male                              7267 non-null   float64
 11  multiplelines_No phone service           7267 non-null   float64
 12  multiplelines_Yes                        7267 non-null   float64
 13  internetservice_DSL                      7267 non-null   float64
 14  internetservice_Fiber optic              7267 non-null   float64
 15  onlinesecurity_No internet service       7267 non-null   float64
 16  onlinesecurity_Yes                       7267 non-null   float64
 17  onlinebackup_No                          7267 non-null   float64
 18  onlinebackup_No internet service         7267 non-null   float64
 19  onlinebackup_Yes                         7267 non-null   float64
 20  deviceprotection_No                      7267 non-null   float64
 21  deviceprotection_No internet service     7267 non-null   float64
 22  deviceprotection_Yes                     7267 non-null   float64
 23  techsupport_No                           7267 non-null   float64
 24  techsupport_No internet service          7267 non-null   float64
 25  techsupport_Yes                          7267 non-null   float64
 26  streamingtv_No                           7267 non-null   float64
 27  streamingtv_No internet service          7267 non-null   float64
 28  streamingtv_Yes                          7267 non-null   float64
 29  streamingmovies_No                       7267 non-null   float64
 30  streamingmovies_No internet service      7267 non-null   float64
 31  streamingmovies_Yes                      7267 non-null   float64
 32  contract_Month-to-month                  7267 non-null   float64
 33  contract_One year                        7267 non-null   float64
 34  contract_Two year                        7267 non-null   float64
 35  paymentmethod_Bank transfer (automatic)  7267 non-null   float64
 36  paymentmethod_Credit card (automatic)    7267 non-null   float64
 37  paymentmethod_Electronic check           7267 non-null   float64
 38  paymentmethod_Mailed check               7267 non-null   float64
dtypes: float64(32), int64(7)
memory usage: 2.2 MB

In [ ]:
datos["charges_total"].isnull().sum()

np.int64(11)

In [ ]:
datos["charges_total"] = datos["charges_total"].fillna(datos["charges_total"].median())

In [ ]:
datos["charges_total"].isnull().sum()

np.int64(0)

###Verificación de la Proporción de Cancelación (Churn)
Calcula la proporción de clientes que cancelaron en relación con los que permanecieron activos. Evalúa si existe un desbalance entre las clases, ya que esto puede impactar en los modelos predictivos y en el análisis de los resultados.

🔎 Sugerencia:
Puedes usar value_counts() de pandas para obtener esta proporción:
Documentación oficial de value_counts()

In [ ]:
datos["churn"].value_counts()

churn
0    5398
1    1869
Name: count, dtype: int64

In [ ]:
datos["churn"].value_counts(normalize=True)

churn
0    0.74281
1    0.25719
Name: proportion, dtype: float64

In [ ]:
churn_proporcion = datos["churn"].value_counts(normalize=True) * 100
churn_proporcion

churn
0    74.280996
1    25.719004
Name: proportion, dtype: float64

Aproximadamente el 26% de los clientes cancelaron el servicio, mientras que el 74% permanecen activos.
Esto indica un desbalance moderado entre las clases, lo cual puede afectar el desempeño de algunos modelos predictivos, especialmente aquellos sensibles al desbalance de clases.

###Balanceo de Clases
Aplicar técnicas de balanceo como undersampling o oversampling. En situaciones de fuerte desbalanceo, herramientas como SMOTE pueden ser útiles para generar ejemplos sintéticos de la clase minoritaria.

In [ ]:
import pandas as pd
from sklearn.utils import resample
from imblearn.over_sampling import SMOTE

# 1. Separar variables
X = datos.drop("churn", axis=1)
y = datos["churn"]

# 2. Verificar proporción de churn
print("Distribución original:")
print(y.value_counts())
print(y.value_counts(normalize=True) * 100)

# 3. Crear dataframe completo
df = pd.concat([X, y], axis=1)

# Separar clases
mayoria = df[df["churn"] == 0]
minoria = df[df["churn"] == 1]

# 4. Undersampling
mayoria_reducida = resample(
    mayoria,
    replace=False,
    n_samples=len(minoria),
    random_state=42
)

datos_undersample = pd.concat([mayoria_reducida, minoria])

print("\nDistribución con Undersampling:")
print(datos_undersample["churn"].value_counts())

# 5. Oversampling
minoria_aumentada = resample(
    minoria,
    replace=True,
    n_samples=len(mayoria),
    random_state=42
)

datos_oversample = pd.concat([mayoria, minoria_aumentada])

print("\nDistribución con Oversampling:")
print(datos_oversample["churn"].value_counts())

# 6. SMOTE
smote = SMOTE(random_state=42)
X_smote, y_smote = smote.fit_resample(X, y)

print("\nDistribución con SMOTE:")
print(pd.Series(y_smote).value_counts())

Distribución original:
churn
0    5398
1    1869
Name: count, dtype: int64
churn
0    74.280996
1    25.719004
Name: proportion, dtype: float64

Distribución con Undersampling:
churn
0    1869
1    1869
Name: count, dtype: int64

Distribución con Oversampling:
churn
0    5398
1    5398
Name: count, dtype: int64

Distribución con SMOTE:
churn
0    5398
1    5398
Name: count, dtype: int64